#https://www.prettier.cn/docs/configuration.html
tabWidth: 2
semi: true
singleQuote: false
trailingComma: all
bracketSpacing: true
bracketSameLine: true
arrowParens: always
printWidth: 120
indentSize: 2